# Generated by Django 4.2.4 on 2023-08-30 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="income",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
