# Generated by Django 4.2.4 on 2023-08-30 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0005_alter_expense_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="user",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incomes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
