# Generated by Django 4.2.4 on 2023-08-31 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0008_alter_expense_category_alter_income_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency_preference",
                    models.CharField(default="Kenyan Shilling (KES)", max_length=100),
                ),
                (
                    "timezone",
                    models.CharField(default="Eastern Time Zone (ET)", max_length=100),
                ),
                (
                    "user",
                    models.OneToOneField(
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
