# Generated by Django 4.2.4 on 2023-08-31 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0009_setting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="user",
            field=models.OneToOneField(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
